Repository Just-Another-Weather-Site/playground, pull requests merged in 2022-08, with the labels that each got.

#13 [issues/6] add basic validation workflow
  .github/workflows/validate.yaml
  composer.json
  composer.lock
Labels: enhancement

#18 Add a Codacy badge to README.md
  README.md
Labels: documentation

#20 [Issues/14] add phpunit CI test
  .github/workflows/ci-coverage.yml
  phpunit.xml
Labels: test or coverage

#24 [issues/17] get and report code coverage
  .github/workflows/ci-coverage.yml
Labels: test or coverage

#27 [issues/19] Cache Composer dependencies for validation
  .github/workflows/ci-coverage.yml
  .github/workflows/validate.yaml
Labels: enhancement, good first issue

#34 [issues/31] add "Github Actions" label
  .github/settings.yml
Labels: repo settings

#33 [Issues/30] add Badges
  README.md
Labels: documentation

#37 [issues/36] auto-approve dependabot / renovate bot
  .github/workflows/auto-approve.yml
Labels: Github Actions

#43 [issues/42] create testcase by downgrading
  composer.json
Labels: test or coverage

#45 [issues/42] create testcase by downgrading
  composer.lock
Labels: test or coverage

#48 [issues/47] try to fix auto-approve by changing trigger
  .github/workflows/auto-approve.yml
Labels: bug, Github Actions

#51 [issues/47] add secrets.GITHUB_TOKEN
  .github/workflows/auto-approve.yml
Labels: bug, Github Actions

#54 [issues/32] .gitattributes added
  .gitattributes
Labels: enhancement
